export interface AdminUser {
    id?: number; // Optional because it's automatically generated by the database.
    username: string;
    password: string; // Note: In a real-world application, we never want to directly handle or store passwords in the front-end. This is just a representation.
    created_at?: Date; // Optional because it's auto-generated with a default value.
  }
  