export interface Meeting {
    id?: number; // Optional because it's automatically generated by the database.
    client_id: number; // This associates a meeting with a client.
    date: Date;
    time: string; // We could also use 'Date' type but this provides more flexibility as you might just want to store time like '15:30'.
    location: string;
    notes?: string; // Optional because notes might not be mandatory.
    created_at?: Date; // Optional because it's auto-generated with a default value.
  }
  